### ISSUE TITLE
how can setup this with r2 

### ISSUE THREAD

**Issue by dungrew1** [longern/FlareDrive#1]
i have read readme.rd but still don't know how to install, please help!!!

**Comment by longern** [comment]
You have to create at least one R2 bucket before setup.
Pages -> `<Your project>` -> Settings -> Functions -> R2 Buckets -> Edit Bindings
Set variable name as subdomain prefix. For example, if your domain is `mydrive.domain.com`, set variable name as `mydrive`. Choose your R2 bucket from list. Save changes and redeploy.
