### ISSUE TITLE
Folder Icon Path 404

### ISSUE THREAD

**Issue by kingal123** [longern/FlareDrive#11]
The URL https://cdnjs.cloudflare.com/ajax/libs/material-design-icons/4.0.0/png/file/folder/materialicons/36dp/2x/baseline_folder_black_36dp.png used for the folder icon is broken. Are you able to take a look please?

**Comment by longern** [comment]
I have tested and the icons load normally, it might be related to the previous incident with cdnjs?

**Comment by kingal123** [comment]
Thanks for confirming it definitely seemed to be a Venus problem
