### ISSUE TITLE
Unable to delete uploaded files

### ISSUE THREAD

**Issue by wsdsbyswq** [longern/FlareDrive#15]
I can't find the file delete button

**Comment by longern** [comment]
Right click or long press, and the delete button is in the multiselect toolbar.

**Comment by wsdsbyswq** [comment]
Thanks, but there's no right click when operating on a mobile browser, so I can't bring up the multiselect toolbar. Is it possible to add a button after the file so that it brings up the multiselect toolbar when clicked?

**Comment by longern** [comment]
On mobile you can just long press on any file or folder item to bring up the toolbar.

**Comment by wsdsbyswq** [comment]
I've tried a couple of Android browsers, and they bring up their own toolbars instead of the web page's original toolbar when long-pressed.
![1](https://github.com/user-attachments/assets/be87faec-988b-4b14-a41c-e48cdc73d487)
![2](https://github.com/user-attachments/assets/0ebe7855-0934-42c6-85c8-860c473080df)

**Comment by longern** [comment]
Add a patch to remove hyperlink on file items. Tested on opera android, edge android.

**Comment by wsdsbyswq** [comment]
Thank you very much! After the update, it works fine on the via browser, but still has problems with Quark, but I think it should be a Quark browser issue.
