### ISSUE TITLE
The sharing feature doesn’t work

### ISSUE THREAD

**Issue by boy86001** [longern/FlareDrive#18]
This network disk can run HTML. I discovered a new world. Hahaha. It's not inferior to the website, but faster.

**Comment by boy86001** [comment]
You can deploy HTML, but others can also download the source code. It would be great if you can only allow access rights but not download them.

**Comment by longern** [comment]
We use `navigator.share` here. Some browsers don't support it but we don't have any plan to support other sharing methods.
