### ISSUE TITLE
How did you setup Cloudflare access Auth?

### ISSUE THREAD

**Issue by kamaravichow** [longern/FlareDrive#4]
It would be great to have a little instructions on the readme

**Comment by longern** [comment]
1. Enable CloudFlare Zero Trust
2. In Access->Applications, create a self-hosted application
3. Set path as `api/write/` to disable public write or leave it blank to disable public read
4. Create a policy which accepts your email only

**Comment by kamaravichow** [comment]
Awesome, thanks
